/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectSelectionRouteImport } from './routes/subject-selection'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SubjectSelectionRoute = SubjectSelectionRouteImport.update({
  id: '/subject-selection',
  path: '/subject-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exam': typeof ExamRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/subject-selection': typeof SubjectSelectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exam': typeof ExamRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/subject-selection': typeof SubjectSelectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exam': typeof ExamRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/subject-selection': typeof SubjectSelectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/exam'
    | '/learn'
    | '/practice'
    | '/products'
    | '/register'
    | '/sign-in'
    | '/subject-selection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/exam'
    | '/learn'
    | '/practice'
    | '/products'
    | '/register'
    | '/sign-in'
    | '/subject-selection'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/exam'
    | '/learn'
    | '/practice'
    | '/products'
    | '/register'
    | '/sign-in'
    | '/subject-selection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExamRoute: typeof ExamRoute
  LearnRoute: typeof LearnRoute
  PracticeRoute: typeof PracticeRoute
  ProductsRoute: typeof ProductsRoute
  RegisterRoute: typeof RegisterRoute
  SignInRoute: typeof SignInRoute
  SubjectSelectionRoute: typeof SubjectSelectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subject-selection': {
      id: '/subject-selection'
      path: '/subject-selection'
      fullPath: '/subject-selection'
      preLoaderRoute: typeof SubjectSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExamRoute: ExamRoute,
  LearnRoute: LearnRoute,
  PracticeRoute: PracticeRoute,
  ProductsRoute: ProductsRoute,
  RegisterRoute: RegisterRoute,
  SignInRoute: SignInRoute,
  SubjectSelectionRoute: SubjectSelectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
